// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1-8KljFrIW1j9kBADD7ZKGuQNHkvUFh8',
    appId: '1:132792273213:web:e5f3112166276ea350dd54',
    messagingSenderId: '132792273213',
    projectId: 'chat-app-8051c',
    authDomain: 'chat-app-8051c.firebaseapp.com',
    storageBucket: 'chat-app-8051c.appspot.com',
    measurementId: 'G-6LETWJ3WFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuyTN9WhLGsLhn1Bp_JM0e4bfEpvwRypM',
    appId: '1:132792273213:android:059d4e62c3c5958f50dd54',
    messagingSenderId: '132792273213',
    projectId: 'chat-app-8051c',
    storageBucket: 'chat-app-8051c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZOHAoHzL3KiVwUW-xXk8_d2NfDTb8QrE',
    appId: '1:132792273213:ios:4a1912e747315d6550dd54',
    messagingSenderId: '132792273213',
    projectId: 'chat-app-8051c',
    storageBucket: 'chat-app-8051c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZOHAoHzL3KiVwUW-xXk8_d2NfDTb8QrE',
    appId: '1:132792273213:ios:4a1912e747315d6550dd54',
    messagingSenderId: '132792273213',
    projectId: 'chat-app-8051c',
    storageBucket: 'chat-app-8051c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1-8KljFrIW1j9kBADD7ZKGuQNHkvUFh8',
    appId: '1:132792273213:web:292c65eea726bd3950dd54',
    messagingSenderId: '132792273213',
    projectId: 'chat-app-8051c',
    authDomain: 'chat-app-8051c.firebaseapp.com',
    storageBucket: 'chat-app-8051c.appspot.com',
    measurementId: 'G-EDX0KGFH7P',
  );
}
